/*
* generated by Xtext
*/
package org.ollabaca.on.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ObjectNotationAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/ollabaca/on/parser/antlr/internal/InternalObjectNotation.tokens");
	}
}
