/*
* generated by Xtext
*/
package org.ollabaca.on.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ollabaca.on.services.ObjectNotationGrammarAccess;

public class ObjectNotationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ObjectNotationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ollabaca.on.parser.antlr.internal.InternalObjectNotationParser createParser(XtextTokenStream stream) {
		return new org.ollabaca.on.parser.antlr.internal.InternalObjectNotationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Unit";
	}
	
	public ObjectNotationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ObjectNotationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
