/*
* generated by Xtext
*/
package org.ollabaca.on.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractObjectNotationJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.ollabaca.on.model.ModelPackage.eINSTANCE);
		return result;
	}

}
