/*
* generated by Xtext
*/

package org.ollabaca.on.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ObjectNotationGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class UnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Unit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Assignment cContainerAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cContainerContainerParserRuleCall_1_0 = (RuleCall)cContainerAssignment_1.eContents().get(0);
		private final Assignment cInstancesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInstancesInstanceParserRuleCall_2_0 = (RuleCall)cInstancesAssignment_2.eContents().get(0);
		
		//Unit:
		//
		//	imports+=Import+ container=Container? instances+=Instance+;
		public ParserRule getRule() { return rule; }

		//imports+=Import+ container=Container? instances+=Instance+
		public Group getGroup() { return cGroup; }

		//imports+=Import+
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//Import
		public RuleCall getImportsImportParserRuleCall_0_0() { return cImportsImportParserRuleCall_0_0; }

		//container=Container?
		public Assignment getContainerAssignment_1() { return cContainerAssignment_1; }

		//Container
		public RuleCall getContainerContainerParserRuleCall_1_0() { return cContainerContainerParserRuleCall_1_0; }

		//instances+=Instance+
		public Assignment getInstancesAssignment_2() { return cInstancesAssignment_2; }

		//Instance
		public RuleCall getInstancesInstanceParserRuleCall_2_0() { return cInstancesInstanceParserRuleCall_2_0; }
	}

	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInstanceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cArrayParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInstanceRefParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLiteralParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Value:
		//
		//	Instance | Array | InstanceRef | Literal;
		public ParserRule getRule() { return rule; }

		//Instance | Array | InstanceRef | Literal
		public Alternatives getAlternatives() { return cAlternatives; }

		//Instance
		public RuleCall getInstanceParserRuleCall_0() { return cInstanceParserRuleCall_0; }

		//Array
		public RuleCall getArrayParserRuleCall_1() { return cArrayParserRuleCall_1; }

		//InstanceRef
		public RuleCall getInstanceRefParserRuleCall_2() { return cInstanceRefParserRuleCall_2; }

		//Literal
		public RuleCall getLiteralParserRuleCall_3() { return cLiteralParserRuleCall_3; }
	}

	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBooleanValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNullValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNumberValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEnumValueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Literal:
		//
		//	StringValue | BooleanValue | NullValue | NumberValue | EnumValue;
		public ParserRule getRule() { return rule; }

		//StringValue | BooleanValue | NullValue | NumberValue | EnumValue
		public Alternatives getAlternatives() { return cAlternatives; }

		//StringValue
		public RuleCall getStringValueParserRuleCall_0() { return cStringValueParserRuleCall_0; }

		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_1() { return cBooleanValueParserRuleCall_1; }

		//NullValue
		public RuleCall getNullValueParserRuleCall_2() { return cNullValueParserRuleCall_2; }

		//NumberValue
		public RuleCall getNumberValueParserRuleCall_3() { return cNumberValueParserRuleCall_3; }

		//EnumValue
		public RuleCall getEnumValueParserRuleCall_4() { return cEnumValueParserRuleCall_4; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameMY_STRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Import:
		//
		//	"import" name=MY_STRING;
		public ParserRule getRule() { return rule; }

		//"import" name=MY_STRING
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//name=MY_STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//MY_STRING
		public RuleCall getNameMY_STRINGTerminalRuleCall_1_0() { return cNameMY_STRINGTerminalRuleCall_1_0; }
	}

	public class ContainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Container");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContainerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInstanceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cInstanceInstanceCrossReference_1_0 = (CrossReference)cInstanceAssignment_1.eContents().get(0);
		private final RuleCall cInstanceInstanceFQNTerminalRuleCall_1_0_1 = (RuleCall)cInstanceInstanceCrossReference_1_0.eContents().get(1);
		private final Keyword cNumberSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFeatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFeatureIDTerminalRuleCall_3_0 = (RuleCall)cFeatureAssignment_3.eContents().get(0);
		
		//Container:
		//
		//	"container" instance=[Instance|FQN] "#" feature=ID;
		public ParserRule getRule() { return rule; }

		//"container" instance=[Instance|FQN] "#" feature=ID
		public Group getGroup() { return cGroup; }

		//"container"
		public Keyword getContainerKeyword_0() { return cContainerKeyword_0; }

		//instance=[Instance|FQN]
		public Assignment getInstanceAssignment_1() { return cInstanceAssignment_1; }

		//[Instance|FQN]
		public CrossReference getInstanceInstanceCrossReference_1_0() { return cInstanceInstanceCrossReference_1_0; }

		//FQN
		public RuleCall getInstanceInstanceFQNTerminalRuleCall_1_0_1() { return cInstanceInstanceFQNTerminalRuleCall_1_0_1; }

		//"#"
		public Keyword getNumberSignKeyword_2() { return cNumberSignKeyword_2; }

		//feature=ID
		public Assignment getFeatureAssignment_3() { return cFeatureAssignment_3; }

		//ID
		public RuleCall getFeatureIDTerminalRuleCall_3_0() { return cFeatureIDTerminalRuleCall_3_0; }
	}

	public class InstanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Instance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInstanceAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cTitleKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTitleAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTitleMY_STRINGTerminalRuleCall_1_1_0 = (RuleCall)cTitleAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractMY_STRINGTerminalRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDocKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDocumentationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDocumentationMY_STRINGTerminalRuleCall_3_1_0 = (RuleCall)cDocumentationAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSeeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSeeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSeeInstanceCrossReference_4_1_0 = (CrossReference)cSeeAssignment_4_1.eContents().get(0);
		private final RuleCall cSeeInstanceFQNTerminalRuleCall_4_1_0_1 = (RuleCall)cSeeInstanceCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_5_0_0 = (RuleCall)cNameAssignment_5_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cNewKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTypeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTypeIDTerminalRuleCall_7_0 = (RuleCall)cTypeAssignment_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSlotsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cSlotsSlotParserRuleCall_9_0 = (RuleCall)cSlotsAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Instance:
		//
		//	{Instance} ("@title" title=MY_STRING)? ("@abstract" abstract=MY_STRING)? ("@doc" documentation=MY_STRING)? ("@see"
		//
		//	see+=[Instance|FQN])* (name=ID "=")? "new" type=ID "{" slots+=Slot* "}";
		public ParserRule getRule() { return rule; }

		//{Instance} ("@title" title=MY_STRING)? ("@abstract" abstract=MY_STRING)? ("@doc" documentation=MY_STRING)? ("@see"
		//
		//see+=[Instance|FQN])* (name=ID "=")? "new" type=ID "{" slots+=Slot* "}"
		public Group getGroup() { return cGroup; }

		//{Instance}
		public Action getInstanceAction_0() { return cInstanceAction_0; }

		//("@title" title=MY_STRING)?
		public Group getGroup_1() { return cGroup_1; }

		//"@title"
		public Keyword getTitleKeyword_1_0() { return cTitleKeyword_1_0; }

		//title=MY_STRING
		public Assignment getTitleAssignment_1_1() { return cTitleAssignment_1_1; }

		//MY_STRING
		public RuleCall getTitleMY_STRINGTerminalRuleCall_1_1_0() { return cTitleMY_STRINGTerminalRuleCall_1_1_0; }

		//("@abstract" abstract=MY_STRING)?
		public Group getGroup_2() { return cGroup_2; }

		//"@abstract"
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }

		//abstract=MY_STRING
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }

		//MY_STRING
		public RuleCall getAbstractMY_STRINGTerminalRuleCall_2_1_0() { return cAbstractMY_STRINGTerminalRuleCall_2_1_0; }

		//("@doc" documentation=MY_STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"@doc"
		public Keyword getDocKeyword_3_0() { return cDocKeyword_3_0; }

		//documentation=MY_STRING
		public Assignment getDocumentationAssignment_3_1() { return cDocumentationAssignment_3_1; }

		//MY_STRING
		public RuleCall getDocumentationMY_STRINGTerminalRuleCall_3_1_0() { return cDocumentationMY_STRINGTerminalRuleCall_3_1_0; }

		//("@see" see+=[Instance|FQN])*
		public Group getGroup_4() { return cGroup_4; }

		//"@see"
		public Keyword getSeeKeyword_4_0() { return cSeeKeyword_4_0; }

		//see+=[Instance|FQN]
		public Assignment getSeeAssignment_4_1() { return cSeeAssignment_4_1; }

		//[Instance|FQN]
		public CrossReference getSeeInstanceCrossReference_4_1_0() { return cSeeInstanceCrossReference_4_1_0; }

		//FQN
		public RuleCall getSeeInstanceFQNTerminalRuleCall_4_1_0_1() { return cSeeInstanceFQNTerminalRuleCall_4_1_0_1; }

		//(name=ID "=")?
		public Group getGroup_5() { return cGroup_5; }

		//name=ID
		public Assignment getNameAssignment_5_0() { return cNameAssignment_5_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_5_0_0() { return cNameIDTerminalRuleCall_5_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }

		//"new"
		public Keyword getNewKeyword_6() { return cNewKeyword_6; }

		//type=ID
		public Assignment getTypeAssignment_7() { return cTypeAssignment_7; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_7_0() { return cTypeIDTerminalRuleCall_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }

		//slots+=Slot*
		public Assignment getSlotsAssignment_9() { return cSlotsAssignment_9; }

		//Slot
		public RuleCall getSlotsSlotParserRuleCall_9_0() { return cSlotsSlotParserRuleCall_9_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class SlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Slot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSlotAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueValueParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//Slot:
		//
		//	{Slot} name=ID "=" value=Value;
		public ParserRule getRule() { return rule; }

		//{Slot} name=ID "=" value=Value
		public Group getGroup() { return cGroup; }

		//{Slot}
		public Action getSlotAction_0() { return cSlotAction_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//value=Value
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }

		//Value
		public RuleCall getValueValueParserRuleCall_3_0() { return cValueValueParserRuleCall_3_0; }
	}

	public class ArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Array");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueValueParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Array:
		//
		//	"[" //( "," value+=Value)*  
		//
		//	value+=Value+ "]";
		public ParserRule getRule() { return rule; }

		//"[" //( "," value+=Value)*  
		//
		//value+=Value+ "]"
		public Group getGroup() { return cGroup; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }

		////( "," value+=Value)*  
		//
		//value+=Value+
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//Value
		public RuleCall getValueValueParserRuleCall_1_0() { return cValueValueParserRuleCall_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
	}

	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueMY_STRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringValue:
		//
		//	value=MY_STRING;
		public ParserRule getRule() { return rule; }

		//value=MY_STRING
		public Assignment getValueAssignment() { return cValueAssignment; }

		//MY_STRING
		public RuleCall getValueMY_STRINGTerminalRuleCall_0() { return cValueMY_STRINGTerminalRuleCall_0; }
	}

	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cValueTrueKeyword_0_0 = (Keyword)cValueAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cValueFalseKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		
		//BooleanValue:
		//
		//	value="true" | value="false";
		public ParserRule getRule() { return rule; }

		//value="true" | value="false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//value="true"
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//"true"
		public Keyword getValueTrueKeyword_0_0() { return cValueTrueKeyword_0_0; }

		//value="false"
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//"false"
		public Keyword getValueFalseKeyword_1_0() { return cValueFalseKeyword_1_0; }
	}

	public class NullValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NullValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNullValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNullKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//NullValue:
		//
		//	{NullValue} "null";
		public ParserRule getRule() { return rule; }

		//{NullValue} "null"
		public Group getGroup() { return cGroup; }

		//{NullValue}
		public Action getNullValueAction_0() { return cNullValueAction_0; }

		//"null"
		public Keyword getNullKeyword_1() { return cNullKeyword_1; }
	}

	public class NumberValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NumberValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueNUMBERTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//NumberValue:
		//
		//	value=NUMBER;
		public ParserRule getRule() { return rule; }

		//value=NUMBER
		public Assignment getValueAssignment() { return cValueAssignment; }

		//NUMBER
		public RuleCall getValueNUMBERTerminalRuleCall_0() { return cValueNUMBERTerminalRuleCall_0; }
	}

	public class InstanceRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InstanceRef");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cValueInstanceCrossReference_0 = (CrossReference)cValueAssignment.eContents().get(0);
		private final RuleCall cValueInstanceFQNTerminalRuleCall_0_1 = (RuleCall)cValueInstanceCrossReference_0.eContents().get(1);
		
		//InstanceRef:
		//
		//	value=[Instance|FQN];
		public ParserRule getRule() { return rule; }

		//value=[Instance|FQN]
		public Assignment getValueAssignment() { return cValueAssignment; }

		//[Instance|FQN]
		public CrossReference getValueInstanceCrossReference_0() { return cValueInstanceCrossReference_0; }

		//FQN
		public RuleCall getValueInstanceFQNTerminalRuleCall_0_1() { return cValueInstanceFQNTerminalRuleCall_0_1; }
	}

	public class EnumValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EnumValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumberSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//EnumValue:
		//
		//	"#" value=ID;
		public ParserRule getRule() { return rule; }

		//"#" value=ID
		public Group getGroup() { return cGroup; }

		//"#"
		public Keyword getNumberSignKeyword_0() { return cNumberSignKeyword_0; }

		//value=ID
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_1_0() { return cValueIDTerminalRuleCall_1_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLONG_STRINGTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//
		//	STRING | LONG_STRING;
		public ParserRule getRule() { return rule; }

		//STRING | LONG_STRING
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//LONG_STRING
		public RuleCall getLONG_STRINGTerminalRuleCall_1() { return cLONG_STRINGTerminalRuleCall_1; }
	}
	
	
	private UnitElements pUnit;
	private ValueElements pValue;
	private LiteralElements pLiteral;
	private ImportElements pImport;
	private ContainerElements pContainer;
	private InstanceElements pInstance;
	private SlotElements pSlot;
	private ArrayElements pArray;
	private StringValueElements pStringValue;
	private BooleanValueElements pBooleanValue;
	private NullValueElements pNullValue;
	private NumberValueElements pNumberValue;
	private InstanceRefElements pInstanceRef;
	private EnumValueElements pEnumValue;
	private EStringElements pEString;
	private TerminalRule tMY_STRING;
	private TerminalRule tNUMBER;
	private TerminalRule tFQN;
	private TerminalRule tID;
	private TerminalRule tLONG_STRING;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ObjectNotationGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.ollabaca.on.ObjectNotation".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Unit:
	//
	//	imports+=Import+ container=Container? instances+=Instance+;
	public UnitElements getUnitAccess() {
		return (pUnit != null) ? pUnit : (pUnit = new UnitElements());
	}
	
	public ParserRule getUnitRule() {
		return getUnitAccess().getRule();
	}

	//Value:
	//
	//	Instance | Array | InstanceRef | Literal;
	public ValueElements getValueAccess() {
		return (pValue != null) ? pValue : (pValue = new ValueElements());
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}

	//Literal:
	//
	//	StringValue | BooleanValue | NullValue | NumberValue | EnumValue;
	public LiteralElements getLiteralAccess() {
		return (pLiteral != null) ? pLiteral : (pLiteral = new LiteralElements());
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}

	//Import:
	//
	//	"import" name=MY_STRING;
	public ImportElements getImportAccess() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//Container:
	//
	//	"container" instance=[Instance|FQN] "#" feature=ID;
	public ContainerElements getContainerAccess() {
		return (pContainer != null) ? pContainer : (pContainer = new ContainerElements());
	}
	
	public ParserRule getContainerRule() {
		return getContainerAccess().getRule();
	}

	//Instance:
	//
	//	{Instance} ("@title" title=MY_STRING)? ("@abstract" abstract=MY_STRING)? ("@doc" documentation=MY_STRING)? ("@see"
	//
	//	see+=[Instance|FQN])* (name=ID "=")? "new" type=ID "{" slots+=Slot* "}";
	public InstanceElements getInstanceAccess() {
		return (pInstance != null) ? pInstance : (pInstance = new InstanceElements());
	}
	
	public ParserRule getInstanceRule() {
		return getInstanceAccess().getRule();
	}

	//Slot:
	//
	//	{Slot} name=ID "=" value=Value;
	public SlotElements getSlotAccess() {
		return (pSlot != null) ? pSlot : (pSlot = new SlotElements());
	}
	
	public ParserRule getSlotRule() {
		return getSlotAccess().getRule();
	}

	//Array:
	//
	//	"[" //( "," value+=Value)*  
	//
	//	value+=Value+ "]";
	public ArrayElements getArrayAccess() {
		return (pArray != null) ? pArray : (pArray = new ArrayElements());
	}
	
	public ParserRule getArrayRule() {
		return getArrayAccess().getRule();
	}

	//StringValue:
	//
	//	value=MY_STRING;
	public StringValueElements getStringValueAccess() {
		return (pStringValue != null) ? pStringValue : (pStringValue = new StringValueElements());
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}

	//BooleanValue:
	//
	//	value="true" | value="false";
	public BooleanValueElements getBooleanValueAccess() {
		return (pBooleanValue != null) ? pBooleanValue : (pBooleanValue = new BooleanValueElements());
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}

	//NullValue:
	//
	//	{NullValue} "null";
	public NullValueElements getNullValueAccess() {
		return (pNullValue != null) ? pNullValue : (pNullValue = new NullValueElements());
	}
	
	public ParserRule getNullValueRule() {
		return getNullValueAccess().getRule();
	}

	//NumberValue:
	//
	//	value=NUMBER;
	public NumberValueElements getNumberValueAccess() {
		return (pNumberValue != null) ? pNumberValue : (pNumberValue = new NumberValueElements());
	}
	
	public ParserRule getNumberValueRule() {
		return getNumberValueAccess().getRule();
	}

	//InstanceRef:
	//
	//	value=[Instance|FQN];
	public InstanceRefElements getInstanceRefAccess() {
		return (pInstanceRef != null) ? pInstanceRef : (pInstanceRef = new InstanceRefElements());
	}
	
	public ParserRule getInstanceRefRule() {
		return getInstanceRefAccess().getRule();
	}

	//EnumValue:
	//
	//	"#" value=ID;
	public EnumValueElements getEnumValueAccess() {
		return (pEnumValue != null) ? pEnumValue : (pEnumValue = new EnumValueElements());
	}
	
	public ParserRule getEnumValueRule() {
		return getEnumValueAccess().getRule();
	}

	//EString returns ecore::EString:
	//
	//	STRING | LONG_STRING;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//terminal MY_STRING:
	//
	//	"\"" ("\\\"" | !"\"")* "\"";
	public TerminalRule getMY_STRINGRule() {
		return (tMY_STRING != null) ? tMY_STRING : (tMY_STRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "MY_STRING"));
	} 

	//terminal NUMBER:
	//
	//	"0" | "-"? "1".."9" "0".."9"* ("." "0".."9"+)? ("e" ("+" | "-") "1".."9" "0".."9"*)?;
	public TerminalRule getNUMBERRule() {
		return (tNUMBER != null) ? tNUMBER : (tNUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NUMBER"));
	} 

	//terminal FQN:
	//
	//	("/" ID)*;
	public TerminalRule getFQNRule() {
		return (tFQN != null) ? tFQN : (tFQN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FQN"));
	} 

	////	ID ('/' ID)*;
	//
	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9" | "-" | ".")*;
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal LONG_STRING:
	//
	//	"(\""->"\")";
	public TerminalRule getLONG_STRINGRule() {
		return (tLONG_STRING != null) ? tLONG_STRING : (tLONG_STRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LONG_STRING"));
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
