/*
 * generated by Xtext
 */
package org.ollabaca.on.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.ollabaca.on.ui.coloring.HighlightingConfiguration;
import org.ollabaca.on.ui.coloring.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ObjectNotationUiModule extends
		org.ollabaca.on.ui.AbstractObjectNotationUiModule {
	public ObjectNotationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return TextHoverProvider.class;
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return DocumentationProvider.class;
	}

	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return HighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return SemanticHighlightingCalculator.class;
	}
}
